### PR TITLE
Updated CI/CD pipeline to use build matrix

### PR DESCRIPTION
**Pull request by nickclark2016**
Use a build matrix to better support parallelization of build pipelines.

### CODE REVIEW

**Comment by charles-lunarg** [comment]
You can remove the submodule update/init stuff, as it now uses cmakes' fetch content stuff exclusively.

**Comment by nickclark2016** [comment]
Done @charles-lunarg. Have we gone ahead and got rid of the dependency on the SDK yet?

**Comment by cdgiessen** [comment]
(oops wrong account)
No, I haven't. But if we are building on ubuntu, we should be using the vulkan packages (headers and loader) instead of the SDK now that I think about it. So using those shouldn't need any code changes in the repo, only ci build setup scripts.

**Comment by cdgiessen** [comment]
vulkan-headers is the headers package. It is from lunarg, so the ppa stuff is still needed.
The `libvulkan1` is what looks to be the loader package.

**Comment by nickclark2016** [comment]
I'd vote that we move to close that in a different PR, and resolve it with a PR for #4

**Comment by cdgiessen** [comment]
I agree, should be a separate PR. I would hope CW can take a look at it since I am not super familiar with CI stuff.

**Comment by nickclark2016** [comment]
I fat fingered @cwfitzgerald, but he can take a look if he wants haha

**Comment by cdgiessen** [comment]
Ah lol, then I should do a double check then approve.

**Pull request merged**
